# Configuración Servidor y BD
spring.application.name=SapereAude
spring.datasource.url=jdbc:postgresql://localhost:5432/sapereaude_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true